<header aria-label="UTHSC Logo" role="banner" class="uthsc-banner hide-for-print">
    <div class="row">
        <div class="medium-10 large-8 small-centered columns">
            <a href="https://uthsc.edu">
                <img src="/images/uthsc-logo-white-text.svg" alt="UTHSC logo" class="uthsc-logo"/>
                <!--<img src="/images/uthsc-campus-logo-horizontal-all-black.svg" alt="UTHSC logo" class="uthsc-logo"/>-->
            </a>
        </div>
    </div>

    <div class="row">
        <div class="hide-for-large columns small-collapse">
            <form class="input-group search-form" aria-label="Search the UTHSC site"
                  action="/search/" method="get">
                <input class="input-group-field search-input"
                       placeholder="Search &hellip;"
                       value=""
                       type="search"
                       aria-label="Search the UTHSC site"
                       role="search"
                       name="q"
                       style="margin-right:0;"/>
                <div class="input-group-button">
                    <button type="submit" class="button" aria-label="Submit search form">
                        <span aria-hidden="true" class="fa fa-search"></span>
                    </button>
                </div>
            </form>
        </div>
    </div>
</header>
