<div class="row uthsc-copy-block text-center medium-text-left collapse medium-uncollapse">
    <div class="columns small-6 medium-3 text-right hide-for-print" aria-label="UTHSC links">
        <ul>
            <li><a href="https://uthsc.edu/give/">Give</a></li>
            <li><a href="https://uthsc.edu/hr/employment/">Employment</a></li>
            <li><a href="https://uthsc.edu/contacts/">Contact</a></li>
        </ul>
    </div>
    <div class="columns small-6 medium-3 text-left hide-for-print" aria-label="UTHSC links">
        <ul>
            <li><a href="https://uthsc.edu/compliance/">Privacy Policy</a></li>
            <li><a href="https://uthsc.edu/policies/">Policies</a></li>
            <li><a href="https://uthsc.edu/students/consumer_info.php">Online Disclosure Statement</a></li>
        </ul>
    </div>
    <div class="columns medium-5" aria-label="UTHSC contact information">
        <p>
            © 2016
            The University of Tennessee Health Science Center<br>
            Memphis, Tennessee 38163<br>
            Main: (901) 448-5500<br>
            TDD: (901) 448-7382
        </p>
    </div>
</div>
<!--Contact info-->
<div class="row hide-for-print">
    <!--Email webmaster-->
    <div class="columns medium-3 medium-push-3">
        <a href="mailto:webmaster@uthsc.edu" class="button expanded uthsc-footer-button">
            <div class="row collapse">
                <div class="columns small-5 text-right">
                    <p><span class="fa fa-envelope fa-3x"></span>&emsp;</p>
                </div>
                <div class="columns small-7 text-left">
                    <p>
                        Email<br/>
                        Webmaster
                    </p>
                </div>
            </div>
        </a>
    </div>
    <!--Edit password-->
    <div class="columns medium-3 medium-pull-3">
        <a href="https://uthsc.edu/password/" class="button expanded uthsc-footer-button">
            <div class="row collapse">
                <div class="columns small-5 text-right">
                    <p><span class="fa fa-key fa-3x"></span>&emsp;</p>
                </div>
                <div class="columns small-7 text-left">
                    <p>
                        Edit<br/>
                        Password
                    </p>
                </div>
            </div>
        </a>
    </div>
</div>
<!--Social media links-->
<div class="row hide-for-print">
    <div class="columns text-center uthsc-social-icons" aria-label="UTHSC on social media">
        <a href="http://facebook.com/uthsc" aria-label="facebook">
            <span class="fa fa-facebook fa-2x fa-inverse"></span>
            <span class="show-for-sr">facebook</span>
        </a>
        <a href="http://twitter.com/uthsc" aria-label="twitter">
            <span class="fa fa-twitter fa-2x fa-inverse"></span>
            <span class="show-for-sr">twitter</span>
        </a>
        <a href="http://instagram.com/uthsc" aria-label="instagram">
            <span class="fa fa-instagram fa-2x fa-inverse"></span>
            <span class="show-for-sr">instagram</span>
        </a>
        <a href="http://linkedin.com/company/university-of-tennessee-health-science-center"
           aria-label="linked in">
            <span class="fa fa-linkedin fa-2x fa-inverse"></span>
            <span class="show-for-sr">linked in</span>
        </a>
        <a href="http://youtube.com/user/uthsc" aria-label="youtube">
            <span class="fa fa-youtube fa-2x fa-inverse"></span>
            <span class="show-for-sr">You-tube</span>
        </a>
        <a href="http://pinterest.com/uthsc/" aria-label="pinterest">
            <span class="fa fa-pinterest fa-2x fa-inverse"></span>
            <span class="show-for-sr">pinterest</span>
        </a>
    </div>
</div>
