<div class="mission-links">
    <h2 class="link-heading">Mission</h2>
    <a href="https://uthsc.edu/academics/index.php"> Academics </a>
    <a href="https://uthsc.edu/research/index.php"> Research </a>
    <a href="https://uthsc.edu/clinical-care/index.php"> Clinical Care </a>
    <a href="https://uthsc.edu/public-service/index.php"> Public Service </a>
</div>
<a class="call-to-action-link" href="https://uthsc.edu/give/"> Make a Gift</a>
<a class="call-to-action-link" href="https://uthsc.edu/admissions/visit-uthsc.php"> Take a Tour</a>
<ul>
    <li><span class="link-heading">Information for...</span>
        <ul>
            <li><a href="https://uthsc.edu/students/index.php">Students</a></li>
            <li><a href="https://uthsc.edu/faculty-staff/index.php">Faculty &amp; Staff</a></li>
            <li><a href="https://uthsc.edu/alumni/">Alumni</a></li>
            <li><a href="https://uthsc.edu/visitors/index.php">Visitors</a></li>
            <li><a href="https://uthsc.edu/clinical-care/index.php">Patients</a></li>
        </ul>
    </li>
    <li><span class="link-heading">Resources</span>
        <ul>
            <li><a href="https://uthsc.edu/banner/info/">Banner</a></li>
            <li><a href="http://courses.uthsc.edu/">Blackboard</a></li>
            <li><a href="https://uthsc.edu/hr/employment/">Career Opportunities</a></li>
            <li><a href="https://uthsc.edu/ilogin/">iLogin</a></li>
            <li><a href="https://irise.uthsc.edu/">iRise</a></li>
            <li><a href="http://library.uthsc.edu/">Library</a></li>
            <li><a href="https://uthsc.edu/map/index.php">Maps</a></li>
            <li><a href="http://utap.tennessee.edu/">MyUT</a></li>
            <li><a href="http://news.uthsc.edu/">News</a></li>
            <li><a href="http://o365.uthsc.edu/">Webmail</a></li>
            <li><a href="http://webdocs.uthsc.edu/">Xythos</a></li>
        </ul>
    </li>
</ul>