<div data-equalizer="heading-links">
    <nav id="uthsc-section-navigation" data-equalizer="nested-links" aria-label="Current section menu" role="navigation"
         class="hide-for-print">
        <ul class="row collapse">
            <li class="uthsc-navigation-column small-2 columns">
                <a href="https://uthsc.edu/academics/index.php" data-equalizer-watch="heading-links">
                    Academics
                </a>
                <ul data-equalizer-watch="nested-links">
                    <li>
                        <a href="https://uthsc.edu/dentistry/">Dentistry</a>
                    </li>
                    <li>
                        <a href="https://uthsc.edu/grad/">Graduate Health Sciences</a>
                    </li>
                    <li>
                        <a href="https://uthsc.edu/health-professions/">Health Professions</a>
                    </li>
                    <li>
                        <a href="http://www.uthsc.edu/Medicine/index.php">Medicine</a>
                    </li>
                    <li>
                        <a href="https://uthsc.edu/nursing/">Nursing</a>
                    </li>
                    <li>
                        <a href="https://uthsc.edu/pharmacy/">Pharmacy</a>
                    </li>
                </ul>
            </li>
            <li class="uthsc-navigation-column small-2 columns">
                <a href="https://uthsc.edu/research/index.php" data-equalizer-watch="heading-links">
                    Research
                </a>
                <ul data-equalizer-watch="nested-links">
                    <li>
                        <a href="https://uthsc.edu/research/about/leadership/index.php">Leadership</a>
                    </li>
                    <li>
                        <a href="https://uthsc.edu/research/sponsored-programs/index.php">Sponsored Programs</a>
                    </li>
                    <li>
                        <a href="https://uthsc.edu/research/compliance/index.php">Compliance</a>
                    </li>
                    <li>
                        <a href="https://uthsc.edu/research/institutional-cores/index.php">Institutional Cores</a>
                    </li>
                    <li>
                        <a href="https://uthsc.edu/research/offices-and-resources/index.php">Offices and Resources</a>
                    </li>
                </ul>
            </li>
            <li class="uthsc-navigation-column small-2 columns">
                <a href="https://uthsc.edu/clinical-care/index.php" data-equalizer-watch="heading-links">
                    Clinical Care
                </a>
                <ul data-equalizer-watch="nested-links">
                    <li>
                        <a href="http://www.universityclinicalhealth.com/">University Clinical Health</a>
                    </li>
                    <li>
                        <a href="https://uthsc.edu/univheal/">University Health Services</a>
                    </li>
                    <li>
                        <a href="http://www.lebonheur.org/ulps/">UT Le Bonheur Pediatric Specialists</a>
                    </li>
                    <li>
                        <a href="http://www.methodisthealth.org/utmp/">UT Methodist Physicians</a>
                    </li>
                    <li>
                        <a href="http://www.regionalonehealth.org/utrop/">UT Regional One Physicians</a>
                    </li>
                </ul>
            </li>
            <li class="uthsc-navigation-column small-2 columns">
                <a href="https://uthsc.edu/public-service/index.php" data-equalizer-watch="heading-links">
                    Public Service
                </a>
                <ul data-equalizer-watch="nested-links"></ul>
            </li>
            <li class="uthsc-navigation-column small-2 columns">
                <a href="https://uthsc.edu/about/index.php" data-equalizer-watch="heading-links">
                    About UTHSC
                </a>
                <ul data-equalizer-watch="nested-links">
                    <li>
                        <a href="https://uthsc.edu/chancellor/index.php">About the Chancellor</a>
                    </li>
                    <li>
                        <a href="https://uthsc.edu/about/mission.php">Mission Statement</a>
                    </li>
                    <li>
                        <a href="https://uthsc.edu/administration/index.php">Administration</a>
                    </li>
                    <li>
                        <a href="https://uthsc.edu/about/campuses.php">Campuses</a>
                    </li>
                    <li>
                        <a href="https://uthsc.edu/about/locations.php">Clinical and Educational Sites</a>
                    </li>
                    <li>
                        <a href="https://uthsc.edu/map/index.php">Campus Map</a>
                    </li>
                </ul>
            </li>
            <li class="uthsc-navigation-column small-2 columns">
                <a href="https://uthsc.edu/alumni/" data-equalizer-watch="heading-links">
                    Alumni and Friends
                </a>
                <ul data-equalizer-watch="nested-links">
                    <li>
                        <a href="http://www.uthscalumni.com/s/1341/uthsc/index.aspx?sid=1341&amp;gid=4&amp;pgid=351">About</a>
                    </li>
                    <li>
                        <a href="http://www.uthscalumni.com/s/1341/uthsc/index.aspx?sid=1341&amp;gid=4&amp;pgid=507">Giving</a>
                    </li>
                    <li>
                        <a href="http://www.uthscalumni.com/s/1341/uthsc/index.aspx?sid=1341&amp;gid=4&amp;pgid=523">Events</a>
                    </li>
                    <li>
                        <a href="http://www.uthscalumni.com/s/1341/uthsc/index.aspx?sid=1341&amp;gid=4&amp;pgid=575">Contact</a>
                    </li>
                </ul>
            </li>
        </ul>
    </nav>
    <div class="uthsc-section-nav-placeholder show-for-large" data-equalizer-watch="heading-links"></div>
</div>