<nav class="uthsc-site-nav hide-for-print" aria-label="UTHSC site menu" role="navigation">
    <div class="uthsc-site-nav-left">
        <ul class="menu">
            <li><a href="https://uthsc.edu/students/index.php">Students</a></li>
            <li><a href="https://uthsc.edu/faculty-staff/index.php">Faculty &amp; Staff</a></li>
            <li><a href="https://uthsc.edu/alumni/">Alumni</a></li>
            <li><a href="https://uthsc.edu/visitors/index.php">Visitors</a></li>
            <li><a href="https://uthsc.edu/clinical-care/index.php">Patients</a></li>
        </ul>
    </div>
    <div class="uthsc-site-nav-right">
        <ul class="dropdown menu" data-dropdown-menu="data-dropdown-menu">
            <li class="has-submenu"><a href="#">Our Mission</a>
                <ul class="submenu menu vertical" data-submenu="data-submenu">
                    <li><a href="https://uthsc.edu/academics/index.php"> Academics </a></li>
                    <li><a href="https://uthsc.edu/research/index.php"> Research </a></li>
                    <li><a href="https://uthsc.edu/clinical-care/index.php"> Clinical Care </a></li>
                    <li><a href="https://uthsc.edu/public-service/index.php"> Public Service </a></li>
                    <li><a href="https://uthsc.edu/about/mission.php"> Mission Statement </a></li>
                </ul>
            </li>
            <li class="has-submenu"><a href="#">Resources</a>
                <ul class="submenu menu vertical" data-submenu="data-submenu">
                    <li><a href="https://uthsc.edu/banner/info/">Banner</a></li>
                    <li><a href="http://courses.uthsc.edu/">Blackboard</a></li>
                    <li><a href="https://uthsc.edu/hr/employment/">Career Opportunities</a></li>
                    <li><a href="https://uthsc.edu/ilogin/">iLogin</a></li>
                    <li><a href="https://irise.uthsc.edu/">iRise</a></li>
                    <li><a href="http://library.uthsc.edu/">Library</a></li>
                    <li><a href="https://uthsc.edu/map/index.php">Maps</a></li>
                    <li><a href="http://utap.tennessee.edu/">MyUT</a></li>
                    <li><a href="http://news.uthsc.edu/">News</a></li>
                    <li><a href="http://o365.uthsc.edu/">Webmail</a></li>
                    <li><a href="http://webdocs.uthsc.edu/">Xythos</a></li>
                </ul>
            </li>
            <li><a href="https://uthsc.edu/give/"> Make a Gift</a></li>
            <li><a href="https://uthsc.edu/admissions/visit-uthsc.php"> Take a Tour</a></li>
            <li>
                <div class="show-for-large">
                    <form class="input-group search-form" aria-label="Search the UTHSC site"
                          action="/search/" method="get">
                        <input class="input-group-field search-input"
                               placeholder="Search &hellip;"
                               value=""
                               type="search"
                               aria-label="Search the UTHSC site"
                               role="search"
                               name="q"
                               style="margin-right:0;"/>
                        <div class="input-group-button">
                            <button type="submit" class="button" aria-label="Submit search form">
                                <span aria-hidden="true" class="fa fa-search"></span>
                            </button>
                        </div>
                    </form>
                </div>
            </li>
        </ul>
    </div>
</nav>