<meta charset="utf-8"/>
<meta http-equiv="x-ua-compatible" content="ie=edge"/>
<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
<link rel="stylesheet" href="/css/uthsc.min.css"/>
<link rel="stylesheet" href="/css/font-awesome.min.css"/>
<link href='https://fonts.googleapis.com/css?family=Open+Sans:300' rel='stylesheet' type='text/css'/>
<link href='https://fonts.googleapis.com/css?family=Roboto:400italic,700italic,300,700,300italic,400' rel='stylesheet'
      type='text/css'/>

<link rel="apple-touch-icon" sizes="57x57" href="/images/favicons/apple-touch-icon-57x57.png?v=bOO6Od2drQ">
<link rel="apple-touch-icon" sizes="60x60" href="/images/favicons/apple-touch-icon-60x60.png?v=bOO6Od2drQ">
<link rel="apple-touch-icon" sizes="72x72" href="/images/favicons/apple-touch-icon-72x72.png?v=bOO6Od2drQ">
<link rel="apple-touch-icon" sizes="76x76" href="/images/favicons/apple-touch-icon-76x76.png?v=bOO6Od2drQ">
<link rel="apple-touch-icon" sizes="114x114" href="/images/favicons/apple-touch-icon-114x114.png?v=bOO6Od2drQ">
<link rel="apple-touch-icon" sizes="120x120" href="/images/favicons/apple-touch-icon-120x120.png?v=bOO6Od2drQ">
<link rel="apple-touch-icon" sizes="144x144" href="/images/favicons/apple-touch-icon-144x144.png?v=bOO6Od2drQ">
<link rel="apple-touch-icon" sizes="152x152" href="/images/favicons/apple-touch-icon-152x152.png?v=bOO6Od2drQ">
<link rel="apple-touch-icon" sizes="180x180" href="/images/favicons/apple-touch-icon-180x180.png?v=bOO6Od2drQ">
<link rel="icon" type="image/png" href="/images/favicons/favicon-32x32.png?v=bOO6Od2drQ" sizes="32x32">
<link rel="icon" type="image/png" href="/images/favicons/android-chrome-192x192.png?v=bOO6Od2drQ" sizes="192x192">
<link rel="icon" type="image/png" href="/images/favicons/favicon-96x96.png?v=bOO6Od2drQ" sizes="96x96">
<link rel="icon" type="image/png" href="/images/favicons/favicon-16x16.png?v=bOO6Od2drQ" sizes="16x16">
<link rel="manifest" href="/images/favicons/manifest.json?v=bOO6Od2drQ">
<link rel="mask-icon" href="/images/favicons/safari-pinned-tab.svg?v=bOO6Od2drQ" color="#006a4d">
<link rel="shortcut icon" href="/images/favicons/favicon.ico?v=bOO6Od2drQ">
<meta name="apple-mobile-web-app-title" content="UTHSC">
<meta name="application-name" content="UTHSC">
<meta name="msapplication-TileColor" content="#efefef">
<meta name="msapplication-TileImage" content="/images/favicons/mstile-144x144.png?v=bOO6Od2drQ">
<meta name="msapplication-config" content="/images/favicons/browserconfig.xml?v=bOO6Od2drQ">
<meta name="theme-color" content="#efefef">
