<!--***********************-->
<!--Emergency Numbers Links-->
<!--***********************-->
<div aria-label="Emergency contact information" class="row collapse hide-for-print" role="complementary">

    <!--Desktop Emergency Numbers Link-->
    <div class="row collapse show-for-medium">
        <div id="uthsc-emergency-desktop" class="medium-5 medium-centered columns">
            <a href="https://uthsc.edu/safety/index.php" class="alert button expanded">
                <div class="row">
                    <div class="columns large-5 medium-4 text-right">
                        <span class="fa fa-phone fa-flip-horizontal fa-3x"></span>
                    </div>

                    <div class="columns large-7 medium-8 text-left">
                        <h2>Emergency<br/>Numbers</h2>
                    </div>

                    <div class="columns">
                        Call 911 or Campus Police at (901) 448-4444<br/> More Emergency Information
                    </div>
                </div>
            </a>
        </div>
    </div>
    <!--/Desktop Emergency Numbers Link-->

    <!--Mobile Emergency Numbers Links-->
    <div id="uthsc-emergency-mobile" class="columns hide-for-medium">
        <h2 class="text-center">
            <span class="fa fa-phone fa-flip-horizontal fa-2x"></span>&emsp;
            Emergency Numbers
        </h2>

        <ul class="accordion emergency-contact" role="tablist"
            data-accordion="data-accordion" data-allow-all-closed="true">

            <!--******************-->
            <!--Medical/Behavioral-->
            <!--******************-->

            <li class="accordion-item" data-accordion-item="data-accordion-item">
                <!-- The tab title needs role="tab", an href, a unique ID, and aria-controls. -->
                <a href="#panel1d" role="tab" class="accordion-title" id="panel1d-heading"
                   aria-controls="panel1d">
                    <span class="fa fa-info-circle"></span> Medical/Behavioral
                </a>

                <!-- The content pane needs an ID that matches the above href, role="tabpanel",
data-tab-content, and aria-labelledby. -->
                <div id="panel1d" class="accordion-content" role="tabpanel" data-tab-content="data-tab-content"
                     aria-labelledby="panel1d-heading">

                    <a href="tel:911" class="button expanded"
                       aria-label="Call police at 911">
                        <span class="fa fa-phone fa-2x fa-flip-horizontal"></span>
                        &emsp;911
                    </a>

                    <p>or Campus Police at</p>

                    <a href="tel:901-448-4444" class="button expanded"
                       aria-label="Call campus police at 901-448-4444">
                        <span class="fa fa-phone fa-2x fa-flip-horizontal"></span>
                        &emsp;(901) 448-4444
                    </a>
                </div>
            </li>
            <!--*******************-->
            <!--/Medical/Behavioral-->
            <!--*******************-->

            <!--*******************-->
            <!--Medical Urgent Care-->
            <!--*******************-->
            <li class="accordion-item" data-accordion-item="data-accordion-item">
                <!-- The tab title needs role="tab", an href, a unique ID, and aria-controls. -->
                <a href="#panel2d" role="tab" class="accordion-title" id="panel2d-heading"
                   aria-controls="panel2d">
                    <span class="fa fa-info-circle"></span> Medical Urgent Care
                </a>

                <!-- The content pane needs an ID that matches the above href, role="tabpanel",
data-tab-content, and aria-labelledby. -->
                <div id="panel2d" class="accordion-content" role="tabpanel" data-tab-content="data-tab-content"
                     aria-labelledby="panel2d-heading">
                    <a href="tel:901-448-5630" class="button expanded"
                       aria-label="Call medical urgent care at 901-448-5630">
                        <span class="fa fa-phone fa-2x fa-flip-horizontal"></span>
                        &emsp;(901) 448-5630
                    </a>
                </div>
            </li>
            <!--********************-->
            <!--/Medical Urgent Care-->
            <!--********************-->

            <!--*****************************-->
            <!--Behavioral Health Urgent Care-->
            <!--*****************************-->
            <li class="accordion-item" data-accordion-item="data-accordion-item">
                <!-- The tab title needs role="tab", an href, a unique ID, and aria-controls. -->
                <a href="#panel3d" role="tab" class="accordion-title" id="panel3d-heading"
                   aria-controls="panel3d">
                    <span class="fa fa-info-circle"></span> Behavioral Health Urgent Care
                </a>

                <!-- The content pane needs an ID that matches the above href, role="tabpanel",
data-tab-content, and aria-labelledby. -->
                <div id="panel3d" class="accordion-content" role="tabpanel" data-tab-content="data-tab-content"
                     aria-labelledby="panel2d-heading">
                    <a href="tel:901-448-5064" class="button expanded"
                       aria-label="Call behavioral health urgent care at 901-448-448-5064">
                        <span class="fa fa-phone fa-2x fa-flip-horizontal"></span>
                        &emsp;(901) 448-5064
                    </a>
                </div>
            </li>
            <!--******************************-->
            <!--/Behavioral Health Urgent Care-->
            <!--******************************-->

            <!--**************************-->
            <!--Student Assistance Program-->
            <!--**************************-->
            <li class="accordion-item" data-accordion-item="data-accordion-item">
                <!-- The tab title needs role="tab", an href, a unique ID, and aria-controls. -->
                <a href="#panel4d" role="tab" class="accordion-title" id="panel4d-heading"
                   aria-controls="panel4d">
                    <span class="fa fa-info-circle"></span> Student Assistance Program
                </a>

                <!-- The content pane needs an ID that matches the above href, role="tabpanel",
data-tab-content, and aria-labelledby. -->
                <div id="panel4d" class="accordion-content" role="tabpanel" data-tab-content="data-tab-content"
                     aria-labelledby="panel4d-heading">

                    <a href="tel:800-327-2255" class="button expanded"
                       aria-label="Call student assistance program at 800-327-2255">
                        <span class="fa fa-phone fa-2x fa-flip-horizontal"></span>
                        &emsp;(800) 327-2255<br/>
                        (Option 3)
                    </a>
                </div>
            </li>
            <!--***************************-->
            <!--/Student Assistance Program-->
            <!--***************************-->

            <!--***************************-->
            <!--Employee Assistance Program-->
            <!--***************************-->
            <li class="accordion-item" data-accordion-item="data-accordion-item">
                <!-- The tab title needs role="tab", an href, a unique ID, and aria-controls. -->
                <a href="#panel5d" role="tab" class="accordion-title" id="panel5d-heading"
                   aria-controls="panel5d">
                    <span class="fa fa-info-circle"></span> Employee Assistance Program
                </a>

                <!-- The content pane needs an ID that matches the above href, role="tabpanel",
data-tab-content, and aria-labelledby. -->
                <div id="panel5d" class="accordion-content" role="tabpanel" data-tab-content="data-tab-content"
                     aria-labelledby="panel5d-heading">

                    <a href="tel:855-437-3486" class="button expanded"
                       aria-label="Call employee assistance program at 855-437-3486">
                        <span class="fa fa-phone fa-2x fa-flip-horizontal"></span>
                        &emsp;(855) 437-3486
                    </a>
                </div>
            </li>
            <!--****************************-->
            <!--/Employee Assistance Program-->
            <!--****************************-->

            <!--******************************-->
            <!--After Hours Medical/Behavioral-->
            <!--******************************-->
            <li class="accordion-item" data-accordion-item="data-accordion-item">
                <!-- The tab title needs role="tab", an href, a unique ID, and aria-controls. -->
                <a href="#panel6d" role="tab" class="accordion-title" id="panel6d-heading"
                   aria-controls="panel6d">
                    <span class="fa fa-info-circle"></span> After Hours Medical/Behavioral
                </a>

                <!-- The content pane needs an ID that matches the above href, role="tabpanel",
data-tab-content, and aria-labelledby. -->
                <div id="panel6d" class="accordion-content" role="tabpanel" data-tab-content="data-tab-content"
                     aria-labelledby="panel6d-heading">

                    <a href="tel:901-541-5654" class="button expanded"
                       aria-label="Call after hours medical behavioral at 901-541-5654">
                        <span class="fa fa-phone fa-2x fa-flip-horizontal"></span>
                        &emsp;(901) 541-5654
                    </a>
                </div>
            </li>
            <!--*******************************-->
            <!--/After Hours Medical/Behavioral-->
            <!--*******************************-->

        </ul>
    </div>
    <!--/Mobile Emergency Numbers Links-->

</div>
